// <auto-generated />
using System;
using LMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316025120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Core.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RequiredCourses")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hoàn thành khóa học đầu tiên",
                            IsDeleted = false,
                            Name = "Người mới bắt đầu",
                            RequiredCourses = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hoàn thành 3 khóa học",
                            IsDeleted = false,
                            Name = "Học viên chăm chỉ",
                            RequiredCourses = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hoàn thành 5 khóa học",
                            IsDeleted = false,
                            Name = "Siêu nhân học tập",
                            RequiredCourses = 5,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hoàn thành 10 khóa học",
                            IsDeleted = false,
                            Name = "Bậc thầy tri thức",
                            RequiredCourses = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LMS.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Kỹ năng mềm",
                            Slug = "ky-nang-mem",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Kỹ thuật",
                            Slug = "ky-thuat",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Quy trình",
                            Slug = "quy-trinh",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Lãnh đạo",
                            Slug = "lanh-dao",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Số hóa",
                            Slug = "so-hoa",
                            SortOrder = 5,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LMS.Core.Entities.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttemptId")
                        .HasColumnType("int");

                    b.Property<string>("CertificateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevokeReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.HasIndex("CertificateCode")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("LMS.Core.Entities.CertificateTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FooterText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UseBuiltInTemplate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("CertificateTemplates");
                });

            modelBuilder.Entity("LMS.Core.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CompletionDeadlineDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EnrollEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("PassScore")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("LMS.Core.Entities.CourseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("CourseGroups");
                });

            modelBuilder.Entity("LMS.Core.Entities.CourseGroupCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("GroupId", "CourseId")
                        .IsUnique();

                    b.ToTable("CourseGroupCourses");
                });

            modelBuilder.Entity("LMS.Core.Entities.DepartmentCourseGroup", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedById")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId", "CourseGroupId");

                    b.HasIndex("CourseGroupId");

                    b.ToTable("DepartmentCourseGroups");
                });

            modelBuilder.Entity("LMS.Core.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccessEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AccessStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("LMS.Core.Entities.DocumentPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanViewCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewHistory")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrantedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("GrantedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentPermissions");
                });

            modelBuilder.Entity("LMS.Core.Entities.DocumentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StorageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadedById");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("DocumentVersions");
                });

            modelBuilder.Entity("LMS.Core.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedById")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GroupEnrollId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("CourseId");

                    b.HasIndex("GroupEnrollId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("LMS.Core.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFreePreview")
                        .HasColumnType("bit");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VideoDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("VideoProvider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VideoStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoStorageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoStorageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("QuizId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("LMS.Core.Entities.LessonAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("StorageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonAttachments");
                });

            modelBuilder.Entity("LMS.Core.Entities.LessonProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("PositionSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WatchedPercent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique();

                    b.ToTable("LessonProgresses");
                });

            modelBuilder.Entity("LMS.Core.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("LMS.Core.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VideoTimestampSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("LMS.Core.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Course",
                            Code = "course.view",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4132),
                            IsDeleted = false,
                            Name = "Xem khóa học",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4133)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Course",
                            Code = "course.create",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4180),
                            IsDeleted = false,
                            Name = "Tạo khóa học",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4192)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Course",
                            Code = "course.edit",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4196),
                            IsDeleted = false,
                            Name = "Sửa khóa học",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4197)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Course",
                            Code = "course.delete",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4200),
                            IsDeleted = false,
                            Name = "Xóa khóa học",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4202)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Course",
                            Code = "course.publish",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4318),
                            IsDeleted = false,
                            Name = "Xuất bản khóa học",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4319)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Enrollment",
                            Code = "enrollment.view",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4339),
                            IsDeleted = false,
                            Name = "Xem ghi danh",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4340)
                        },
                        new
                        {
                            Id = 7,
                            Category = "Enrollment",
                            Code = "enrollment.approve",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4343),
                            IsDeleted = false,
                            Name = "Duyệt ghi danh",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4344)
                        },
                        new
                        {
                            Id = 8,
                            Category = "Enrollment",
                            Code = "enrollment.assign",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4347),
                            IsDeleted = false,
                            Name = "Gán học viên",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4347)
                        },
                        new
                        {
                            Id = 9,
                            Category = "Document",
                            Code = "doc.view",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4350),
                            IsDeleted = false,
                            Name = "Xem tài liệu",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4351)
                        },
                        new
                        {
                            Id = 10,
                            Category = "Document",
                            Code = "doc.upload",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4357),
                            IsDeleted = false,
                            Name = "Tải tài liệu",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4357)
                        },
                        new
                        {
                            Id = 11,
                            Category = "Document",
                            Code = "doc.delete",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4360),
                            IsDeleted = false,
                            Name = "Xóa tài liệu",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4361)
                        },
                        new
                        {
                            Id = 12,
                            Category = "Quiz",
                            Code = "quiz.create",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4363),
                            IsDeleted = false,
                            Name = "Tạo bài tập",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4364)
                        },
                        new
                        {
                            Id = 13,
                            Category = "Quiz",
                            Code = "quiz.manage",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4367),
                            IsDeleted = false,
                            Name = "Quản lý bài tập",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4368)
                        },
                        new
                        {
                            Id = 14,
                            Category = "Report",
                            Code = "report.view",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4371),
                            IsDeleted = false,
                            Name = "Xem báo cáo",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4372)
                        },
                        new
                        {
                            Id = 15,
                            Category = "Admin",
                            Code = "user.manage",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4375),
                            IsDeleted = false,
                            Name = "Quản lý người dùng",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4375)
                        },
                        new
                        {
                            Id = 16,
                            Category = "Admin",
                            Code = "role.manage",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4378),
                            IsDeleted = false,
                            Name = "Quản lý phân quyền",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4379)
                        },
                        new
                        {
                            Id = 17,
                            Category = "Admin",
                            Code = "group.manage",
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4381),
                            IsDeleted = false,
                            Name = "Quản lý nhóm",
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4382)
                        });
                });

            modelBuilder.Entity("LMS.Core.Entities.QAThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("QAThreads");
                });

            modelBuilder.Entity("LMS.Core.Entities.QuestionBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Points")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuestionBanks");
                });

            modelBuilder.Entity("LMS.Core.Entities.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttemptWindowHours")
                        .HasColumnType("int");

                    b.Property<int?>("AvailableFromDays")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxAttemptsPerWindow")
                        .HasColumnType("int");

                    b.Property<int>("PassScore")
                        .HasColumnType("int");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("QuizEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("QuizStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ShuffleAnswers")
                        .HasColumnType("bit");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("bit");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("LMS.Core.Entities.QuizAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedAnswer")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique();

                    b.ToTable("QuizAnswers");
                });

            modelBuilder.Entity("LMS.Core.Entities.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int?>("RemainingSeconds")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("LMS.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quản trị viên hệ thống",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Admin",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giảng viên",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Instructor",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nhân viên / Học viên",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "Employee",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LMS.Core.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrantedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4995),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4993),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4995)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4999),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4998),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4999)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5001),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5000),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5001)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5003),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5002),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5003)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5005),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5004),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5006)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5007),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5006),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5008)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5009),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5008),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5010)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5011),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5011),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5012)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5013),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5013),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5014)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5015),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5015),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5016)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5017),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5017),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5018)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5019),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5019),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5020)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5021),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5020),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5022)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5023),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5022),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5024)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5025),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5024),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5026)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5027),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5026),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5028)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17,
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5029),
                            GrantedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5028),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(5030)
                        });
                });

            modelBuilder.Entity("LMS.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeactivatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@lms.com",
                            FullName = "Admin",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$gZ9Zo0JwV0sVH7oWzQkBJ.6522nMWjjs/unVzaY6eEmp1snMMPqku",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LMS.Core.Entities.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("LMS.Core.Entities.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("LMS.Core.Entities.UserGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AddedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("UserGroupMembers");
                });

            modelBuilder.Entity("LMS.Core.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4609),
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 3, 16, 2, 51, 16, 775, DateTimeKind.Utc).AddTicks(4609)
                        });
                });

            modelBuilder.Entity("LMS.Core.Entities.Certificate", b =>
                {
                    b.HasOne("LMS.Core.Entities.QuizAttempt", "Attempt")
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Core.Entities.Course", "Course")
                        .WithMany("Certificates")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.User", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Core.Entities.CertificateTemplate", b =>
                {
                    b.HasOne("LMS.Core.Entities.Course", "Course")
                        .WithOne("CertificateTemplate")
                        .HasForeignKey("LMS.Core.Entities.CertificateTemplate", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMS.Core.Entities.Course", b =>
                {
                    b.HasOne("LMS.Core.Entities.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LMS.Core.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LMS.Core.Entities.CourseGroup", b =>
                {
                    b.HasOne("LMS.Core.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LMS.Core.Entities.CourseGroupCourse", b =>
                {
                    b.HasOne("LMS.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.CourseGroup", "Group")
                        .WithMany("Courses")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LMS.Core.Entities.DepartmentCourseGroup", b =>
                {
                    b.HasOne("LMS.Core.Entities.CourseGroup", "CourseGroup")
                        .WithMany()
                        .HasForeignKey("CourseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.UserGroup", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseGroup");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LMS.Core.Entities.Document", b =>
                {
                    b.HasOne("LMS.Core.Entities.DocumentVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Core.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentVersion");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("LMS.Core.Entities.DocumentPermission", b =>
                {
                    b.HasOne("LMS.Core.Entities.Document", "Document")
                        .WithMany("Permissions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.User", "GrantedBy")
                        .WithMany()
                        .HasForeignKey("GrantedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Core.Entities.UserGroup", "UserGroup")
                        .WithMany()
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Document");

                    b.Navigation("GrantedBy");

                    b.Navigation("Role");

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("LMS.Core.Entities.DocumentVersion", b =>
                {
                    b.HasOne("LMS.Core.Entities.Document", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("LMS.Core.Entities.Enrollment", b =>
                {
                    b.HasOne("LMS.Core.Entities.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LMS.Core.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.UserGroup", "GroupEnroll")
                        .WithMany("GroupEnrollments")
                        .HasForeignKey("GroupEnrollId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LMS.Core.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("Course");

                    b.Navigation("GroupEnroll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Core.Entities.Lesson", b =>
                {
                    b.HasOne("LMS.Core.Entities.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId");

                    b.Navigation("Module");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("LMS.Core.Entities.LessonAttachment", b =>
                {
                    b.HasOne("LMS.Core.Entities.Lesson", "Lesson")
                        .WithMany("Attachments")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LMS.Core.Entities.LessonProgress", b =>
                {
                    b.HasOne("LMS.Core.Entities.Lesson", "Lesson")
                        .WithMany("Progresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.User", "User")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Core.Entities.Module", b =>
                {
                    b.HasOne("LMS.Core.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMS.Core.Entities.Note", b =>
                {
                    b.HasOne("LMS.Core.Entities.Lesson", "Lesson")
                        .WithMany("Notes")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Core.Entities.QAThread", b =>
                {
                    b.HasOne("LMS.Core.Entities.Lesson", "Lesson")
                        .WithMany("QAThreads")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.QAThread", "Parent")
                        .WithMany("Replies")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Core.Entities.User", "User")
                        .WithMany("QAThreads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Core.Entities.QuestionBank", b =>
                {
                    b.HasOne("LMS.Core.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("LMS.Core.Entities.Quiz", b =>
                {
                    b.HasOne("LMS.Core.Entities.Course", "Course")
                        .WithMany("Quizzes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LMS.Core.Entities.QuizAnswer", b =>
                {
                    b.HasOne("LMS.Core.Entities.QuizAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.QuestionBank", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LMS.Core.Entities.QuizAttempt", b =>
                {
                    b.HasOne("LMS.Core.Entities.Quiz", "Quiz")
                        .WithMany("Attempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("LMS.Core.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LMS.Core.Entities.UserBadge", b =>
                {
                    b.HasOne("LMS.Core.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Core.Entities.UserGroup", b =>
                {
                    b.HasOne("LMS.Core.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LMS.Core.Entities.UserGroupMember", b =>
                {
                    b.HasOne("LMS.Core.Entities.User", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LMS.Core.Entities.UserGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Core.Entities.UserRole", b =>
                {
                    b.HasOne("LMS.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Core.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("LMS.Core.Entities.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("LMS.Core.Entities.Course", b =>
                {
                    b.Navigation("CertificateTemplate");

                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");

                    b.Navigation("Modules");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("LMS.Core.Entities.CourseGroup", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("LMS.Core.Entities.Document", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("LMS.Core.Entities.Lesson", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Notes");

                    b.Navigation("Progresses");

                    b.Navigation("QAThreads");
                });

            modelBuilder.Entity("LMS.Core.Entities.Module", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("LMS.Core.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LMS.Core.Entities.QAThread", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("LMS.Core.Entities.QuestionBank", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("LMS.Core.Entities.Quiz", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LMS.Core.Entities.QuizAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("LMS.Core.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LMS.Core.Entities.User", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");

                    b.Navigation("LessonProgresses");

                    b.Navigation("Notes");

                    b.Navigation("QAThreads");

                    b.Navigation("QuizAttempts");

                    b.Navigation("UserBadges");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LMS.Core.Entities.UserGroup", b =>
                {
                    b.Navigation("GroupEnrollments");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
